import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {rehearse,TOOL_ID,LIMITS} from '../src/index.mjs';

const snapshot=()=>({schemaVersion:'1',complete:true,fixture:{tables:[]},steps:{setup:[{action:'create-table',table:'items',columns:['id']}],forward:[{action:'add-column',table:'items',column:'label'}],rollback:[{action:'remove-column',table:'items',column:'label'}]},expected:{afterSetup:{tables:[{name:'items',columns:['id']}]},afterForward:{tables:[{name:'items',columns:['id','label']}]},afterRollback:{tables:[{name:'items',columns:['id']}]}}});
const run=(root,file='snapshot.json')=>spawnSync(process.execPath,['bin/migration-rehearsal-runner.mjs','--root',root,'--input',file],{encoding:'utf8'});

test('declared setup, forward and rollback simulation passes without changing fixture',()=>{
  const d=snapshot(),before=JSON.stringify(d),r=rehearse(d,{now:()=>0});assert.equal(TOOL_ID,'migration-rehearsal-runner');assert.equal(r.status,'pass');assert.equal(r.summary.checked,3);assert.deepEqual(r.disposal,{scope:'simulated-memory-only',performed:true});assert.equal(r.failure,null);assert.equal(JSON.stringify(d),before);assert.doesNotMatch(JSON.stringify(r),/items|label/);
});
test('failing forward step retains phase and pointer while disposing only simulated state',()=>{
  const d=snapshot();d.steps.forward[0].column='id';const r=rehearse(d,{now:()=>0});assert.equal(r.status,'fail');assert.ok(r.findings.some(x=>x.ruleId==='step-failed'&&x.location.pointer==='/steps/forward/0'));assert.deepEqual(r.failure,{phase:'forward',step:'/steps/forward/0'});assert.deepEqual(r.disposal,{scope:'simulated-memory-only',performed:true});assert.deepEqual(d.fixture.tables,[]);
});
test('unavailable rollback and unsupported SQL or connection fields are incomplete',()=>{
  const d=snapshot();d.steps.rollback=[];let r=rehearse(d,{now:()=>0});assert.equal(r.status,'incomplete');assert.ok(r.findings.some(x=>x.ruleId==='rollback-unavailable'));d.steps.rollback=snapshot().steps.rollback;d.databaseUrl='postgres://synthetic.invalid/db';r=rehearse(d,{now:()=>0});assert.equal(r.status,'incomplete');assert.doesNotMatch(JSON.stringify(r),/postgres|synthetic/);delete d.databaseUrl;d.metadata={note:'sqlite:///synthetic.db'};assert.equal(rehearse(d,{now:()=>0}).status,'incomplete');d.metadata.note='  postgresql://synthetic:synthetic@db.invalid/test';r=rehearse(d,{now:()=>0});assert.equal(r.status,'incomplete');assert.doesNotMatch(JSON.stringify(r),/synthetic|db\.invalid/);d.metadata.note='Example connection: postgresql://synthetic.invalid/db';assert.equal(rehearse(d,{now:()=>0}).status,'incomplete');d.metadata.note='migration docs mention PostgreSQL and table changes';assert.equal(rehearse(d,{now:()=>0}).status,'pass');delete d.metadata;d.steps.forward[0]={action:'sql',sql:'DROP TABLE items'};assert.equal(rehearse(d,{now:()=>0}).status,'incomplete');
});
test('declared expected state must match; malformed or duplicate schemas cannot pass',()=>{
  const d=snapshot();d.expected.afterForward.tables[0].columns=['id'];let r=rehearse(d,{now:()=>0});assert.equal(r.status,'fail');assert.ok(r.findings.some(x=>x.ruleId==='state-mismatch'));d.expected.afterForward.tables[0].columns=['id','label','label'];assert.equal(rehearse(d,{now:()=>0}).status,'incomplete');d.expected.afterForward.tables[0].columns=['id','label'];d.complete=false;assert.equal(rehearse(d,{now:()=>0}).status,'incomplete');
});
test('rollback must restore post-setup baseline, not merely a convenient expected state',()=>{
  const d=snapshot();d.steps.rollback[0].column='id';d.expected.afterRollback.tables[0].columns=['label'];const r=rehearse(d,{now:()=>0});assert.equal(r.status,'fail');assert.ok(r.findings.some(x=>x.ruleId==='rollback-not-restored'));
});
test('table, column, step, depth and deadline bounds accept N and reject N+1',()=>{
  const d=snapshot();d.fixture.tables=Array.from({length:LIMITS.tables},(_,i)=>({name:`t${i}`,columns:['id']}));d.steps.setup=[];d.expected.afterSetup=structuredClone(d.fixture);d.expected.afterForward=structuredClone(d.fixture);d.expected.afterForward.tables[0].columns.push('label');d.expected.afterRollback=structuredClone(d.fixture);d.steps.forward=[{action:'add-column',table:'t0',column:'label'}];d.steps.rollback=[{action:'remove-column',table:'t0',column:'label'}];assert.equal(rehearse(d,{now:()=>0}).status,'pass');d.fixture.tables.push({name:'extra',columns:['id']});assert.equal(rehearse(d,{now:()=>0}).findings[0].ruleId,'record-limit');
  const c=snapshot();c.fixture.tables=[{name:'wide',columns:Array.from({length:LIMITS.columns},(_,i)=>`c${i}`)},{name:'items',columns:['id']}];c.steps.setup=[];c.expected.afterSetup=structuredClone(c.fixture);c.expected.afterForward=structuredClone(c.fixture);c.expected.afterForward.tables[1].columns.push('label');c.expected.afterRollback=structuredClone(c.fixture);assert.equal(rehearse(c,{now:()=>0}).status,'pass');c.fixture.tables[0].columns.push('extra');assert.equal(rehearse(c,{now:()=>0}).findings[0].ruleId,'record-limit');
  const s=snapshot();s.steps.setup=[];s.fixture.tables=[{name:'items',columns:['id']}];s.expected.afterSetup=structuredClone(s.fixture);s.steps.forward=Array.from({length:LIMITS.steps},(_,i)=>({action:'add-column',table:'items',column:`c${i}`}));s.expected.afterForward.tables[0].columns=['id',...s.steps.forward.map(x=>x.column)];s.steps.rollback=s.steps.forward.toReversed().map(x=>({action:'remove-column',table:'items',column:x.column}));s.expected.afterRollback=structuredClone(s.fixture);assert.equal(rehearse(s,{now:()=>0}).status,'pass');s.steps.forward.push({action:'add-column',table:'items',column:'extra'});assert.equal(rehearse(s,{now:()=>0}).findings[0].ruleId,'record-limit');
  const z=snapshot();z.metadata={};let x=z.metadata;for(let i=1;i<LIMITS.depth;i++){x.next={};x=x.next;}assert.equal(rehearse(z,{now:()=>0}).status,'pass');x.next={};assert.equal(rehearse(z,{now:()=>0}).findings[0].ruleId,'depth-limit');
  const named=JSON.parse(JSON.stringify(snapshot()).replaceAll('items','a'.repeat(64)));assert.equal(rehearse(named,{now:()=>0}).status,'pass');const overNamed=JSON.parse(JSON.stringify(snapshot()).replaceAll('items','a'.repeat(65)));assert.equal(rehearse(overNamed,{now:()=>0}).status,'incomplete');
  let tick=0;assert.equal(rehearse(snapshot(),{now:()=>tick++?LIMITS.milliseconds:0}).status,'pass');tick=0;assert.equal(rehearse(snapshot(),{now:()=>tick++?LIMITS.milliseconds+1:0}).findings[0].ruleId,'time-limit');
});
test('CLI examples, byte N/N+1, duplicate keys, invalid UTF-8 and confinement',()=>{
  let r=run(path.resolve('examples/pass'));assert.equal(r.status,0);assert.equal(JSON.parse(r.stdout).status,'pass');r=run(path.resolve('examples/fail'));assert.equal(r.status,1);assert.equal(JSON.parse(r.stdout).status,'fail');
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'migration-rehearsal-'));try{
    const d=snapshot();let raw=JSON.stringify(d);fs.writeFileSync(path.join(dir,'snapshot.json'),raw);assert.equal(run(dir).status,0);fs.writeFileSync(path.join(dir,'snapshot.json'),raw.replace('"complete":true','"com\\u0070lete":false,"complete":true'));r=run(dir);assert.equal(r.status,2);assert.equal(JSON.parse(r.stdout).status,'incomplete');fs.writeFileSync(path.join(dir,'snapshot.json'),Buffer.from([0x7b,0xff,0x7d]));r=run(dir);assert.equal(r.status,2);assert.equal(JSON.parse(r.stdout).findings[0].ruleId,'input-invalid');
    raw=JSON.stringify({...d,metadata:{padding:'x'.repeat(Math.max(0,LIMITS.bytes-Buffer.byteLength(JSON.stringify({...d,metadata:{padding:''}}))))}});fs.writeFileSync(path.join(dir,'snapshot.json'),raw);assert.equal(fs.statSync(path.join(dir,'snapshot.json')).size,LIMITS.bytes);assert.equal(run(dir).status,0);fs.appendFileSync(path.join(dir,'snapshot.json'),' ');r=run(dir);assert.equal(r.status,2);assert.equal(JSON.parse(r.stdout).findings[0].ruleId,'byte-limit');
    r=run('/definitely-not-existing-rehearsal-root');assert.equal(r.status,2);assert.equal(r.stdout,'');const outside=fs.mkdtempSync(path.join(os.tmpdir(),'rehearsal-outside-'));try{fs.writeFileSync(path.join(outside,'snapshot.json'),JSON.stringify(d));fs.symlinkSync(path.join(outside,'snapshot.json'),path.join(dir,'link.json'));r=run(dir,'link.json');assert.equal(r.status,2);assert.equal(JSON.parse(r.stdout).status,'incomplete');}finally{fs.rmSync(outside,{recursive:true,force:true});}
  }finally{fs.rmSync(dir,{recursive:true,force:true});}
});
